### ISSUE TITLE
Error when SSID contains directory characters

### ISSUE THREAD

**Issue by A1rPun** [kevva/wifi-password-cli#1]
When I try to retrieve the password of the SSID `/\/\r.g33l<` I get the following error:
```
$ wifi-password
```
```
Error: Command failed: sudo cat /etc/NetworkManager/system-connections//\/\r.g33l<
cat: '/etc/NetworkManager/system-connections//\/\r.g33l<': No such file or directory

    at Promise.all.then.arr (/usr/lib/node_modules/wifi-password-cli/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by A1rPun** [comment]
I'll close this here because I think `wifi-password` is responsible for the issue. The concatenation of directory & SSID happens there
